import React from 'react';
import { Shield, Mail, Phone, MapPin } from '../icons';
import { useScrollAnimation } from '../hooks/useScrollAnimation';

const PrivacyPolicy = () => {
  const ref = useScrollAnimation();

  return (
    <div className="min-h-screen bg-black">
      {/* Hero Section */}
      <section className="section-padding bg-gradient-animated grid-pattern pt-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div ref={ref} className="text-center fade-in">
            <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-primary rounded-full text-black mb-6">
              <Shield className="h-8 w-8" />
            </div>
            <h1 className="font-poppins font-bold text-4xl md:text-6xl lg:text-7xl text-white mb-6">
              Privacy <span className="text-gradient">Policy</span>
            </h1>
            <p className="text-xl text-gray-300 max-w-3xl mx-auto leading-relaxed">
              Your privacy is important to us. This policy explains how we collect, use, and protect your information.
            </p>
          </div>
        </div>
      </section>

      {/* Privacy Policy Content */}
      <section className="section-padding bg-gray-900">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="dark-card p-8 md:p-12 fade-in">
            <div className="prose prose-invert max-w-none">
              <p className="text-gray-400 mb-8">Last updated: June 26, 2025</p>
              
              <div className="space-y-8 text-gray-300 leading-relaxed">
                <p>
                  This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>
                
                <p>
                  We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
                </p>

                <div>
                  <h2 className="font-poppins font-semibold text-2xl text-white mb-4">Interpretation and Definitions</h2>
                  
                  <h3 className="font-poppins font-semibold text-xl text-white mb-3">Interpretation</h3>
                  <p className="mb-4">
                    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                  </p>

                  <h3 className="font-poppins font-semibold text-xl text-white mb-3">Definitions</h3>
                  <p className="mb-4">For the purposes of this Privacy Policy:</p>
                  
                  <ul className="space-y-3 mb-6">
                    <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                    <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                    <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Qyuki Digital Media, 402/404, 4th floor, Tower No. 2, STAR HUB COMPLEX, near Itc Maratha, Sahar Village, Andheri East, Mumbai, Maharashtra 400059.</li>
                    <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                    <li><strong>Country</strong> refers to: Maharashtra, India</li>
                    <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                    <li><strong>Service</strong> refers to the Website.</li>
                    <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li><strong>Website</strong> refers to Qyuki AI, accessible from qyuki.ai</li>
                    <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                  </ul>
                </div>

                <div>
                  <h2 className="font-poppins font-semibold text-2xl text-white mb-4">Collecting and Using Your Personal Data</h2>
                  
                  <h3 className="font-poppins font-semibold text-xl text-white mb-3">Types of Data Collected</h3>
                  
                  <h4 className="font-poppins font-semibold text-lg text-white mb-3">Personal Data</h4>
                  <p className="mb-4">
                    While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: Usage Data.
                  </p>

                  <h4 className="font-poppins font-semibold text-lg text-white mb-3">Usage Data</h4>
                  <p className="mb-4">Usage Data is collected automatically when using the Service.</p>
                  <p className="mb-4">
                    Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                  </p>
                  <p className="mb-4">
                    When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                  </p>
                  <p className="mb-6">
                    We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                  </p>
                </div>

                <div>
                  <h3 className="font-poppins font-semibold text-xl text-white mb-3">Tracking Technologies and Cookies</h3>
                  <p className="mb-4">
                    We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
                  </p>
                  
                  <ul className="space-y-3 mb-6">
                    <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                    <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
                  </ul>

                  <p className="mb-4">
                    Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
                  </p>

                  <p className="mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>
                  
                  <div className="space-y-4 mb-6">
                    <div>
                      <h5 className="font-semibold text-white mb-2">Necessary / Essential Cookies</h5>
                      <p><strong>Type:</strong> Session Cookies</p>
                      <p><strong>Administered by:</strong> Us</p>
                      <p><strong>Purpose:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
                    </div>
                    
                    <div>
                      <h5 className="font-semibold text-white mb-2">Cookies Policy / Notice Acceptance Cookies</h5>
                      <p><strong>Type:</strong> Persistent Cookies</p>
                      <p><strong>Administered by:</strong> Us</p>
                      <p><strong>Purpose:</strong> These Cookies identify if users have accepted the use of cookies on the Website.</p>
                    </div>
                    
                    <div>
                      <h5 className="font-semibold text-white mb-2">Functionality Cookies</h5>
                      <p><strong>Type:</strong> Persistent Cookies</p>
                      <p><strong>Administered by:</strong> Us</p>
                      <p><strong>Purpose:</strong> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
                    </div>
                  </div>
                </div>

                <div>
                  <h3 className="font-poppins font-semibold text-xl text-white mb-3">Use of Your Personal Data</h3>
                  <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
                  
                  <ul className="space-y-3 mb-6">
                    <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                    <li>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                    <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                    <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                    <li>To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
                    <li>To manage Your requests: To attend and manage Your requests to Us.</li>
                    <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
                    <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-poppins font-semibold text-xl text-white mb-3">Security of Your Personal Data</h3>
                  <p className="mb-6">
                    The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                  </p>
                </div>

                <div>
                  <h3 className="font-poppins font-semibold text-xl text-white mb-3">Children's Privacy</h3>
                  <p className="mb-6">
                    Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
                  </p>
                </div>

                <div>
                  <h3 className="font-poppins font-semibold text-xl text-white mb-3">Changes to this Privacy Policy</h3>
                  <p className="mb-4">
                    We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
                  </p>
                  <p className="mb-6">
                    We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Contact Section */}
      <section className="section-padding bg-black">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12 fade-in">
            <h2 className="font-poppins font-bold text-3xl md:text-4xl text-white mb-4">
              Contact <span className="text-gradient">Us</span>
            </h2>
            <p className="text-lg text-gray-400">
              If you have any questions about this Privacy Policy, you can contact us:
            </p>
          </div>

          <div className="dark-card p-8 text-center fade-in">
            <div className="flex items-center justify-center mb-6">
              <Mail className="h-6 w-6 text-gradient mr-3" />
              <span className="text-white font-medium">rohan.sawant@qyuki.com</span>
            </div>
            
            <div className="flex items-center justify-center mb-6">
              <MapPin className="h-6 w-6 text-gradient mr-3" />
              <span className="text-gray-300 text-sm">
                402/404, 4th floor, Tower No. 2, STAR HUB COMPLEX,<br />
                near Itc Maratha, Sahar Village, Andheri East,<br />
                Mumbai, Maharashtra 400059
              </span>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default PrivacyPolicy;